#!/bin/bash
#format the storage for namenode.
hadoop namenode -format

#START DEAMONS
hadoop-daemon.sh start namenode
hadoop-daemon.sh start datanode
hadoop-daemon.sh start secondarynamenode
yarn-daemon.sh start resourcemanager
yarn-daemon.sh start nodemanager
mr-jobhistory-daemon.sh start historyserver
'jps'

#mkdir input                                # create a local folder
#vim input/file                             # create and edit a file. Type down some words in the file.
hdfs dfs -copyFromLocal ./input/ /input/    # copy the local directory to HDFS
hdfs dfs -ls /input/                         # list the files in the directory /input on HDFS

# run the famous hadoop example
hadoop jar hadoop-2.6.1/share/hadoop/mapreduce/hadoop-mapreduce-examples-2.6.1.jar wordcount /input /output 
hdfs dfs -ls /output                    # you should see all the outputs
hdfs dfs -copyToLocal /output           # download the result from HDFS

#STOP DEAMONS
hadoop-daemon.sh stop namenode
hadoop-daemon.sh stop datanode
hadoop-daemon.sh stop secondarynamenode
yarn-daemon.sh stop resourcemanager
yarn-daemon.sh stop nodemanager
mr-jobhistory-daemon.sh stop historyserver
'jps'
